# Generated by Django 4.2.30 on 2026-06-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileasset_poster_path_album_fileasset_album_and_more'),
        ('accounts', '0004_dictionaryentry_dictionaryprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='active_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_profiles', to='files.album'),
        ),
    ]
