# Generated by Django 5.2.13 on 2026-05-03 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web'), ('system', 'System')], default='web', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('ready', 'Готов'), ('failed', 'Ошибка'), ('deleted', 'Удалён')], default='pending', max_length=20)),
                ('telegram_file_id', models.CharField(blank=True, max_length=255)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='files_filea_owner_i_e86185_idx'), models.Index(fields=['category', '-created_at'], name='files_filea_categor_3642de_idx'), models.Index(fields=['status', '-created_at'], name='files_filea_status_fc44ce_idx')],
            },
        ),
    ]
