# Generated by Django 5.2.13 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='storage_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
