# Generated by Django 4.2.30 on 2026-06-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_alter_fileasset_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='poster_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fileasset',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.album'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['owner', '-created_at'], name='files_album_owner_i_fe633f_idx'),
        ),
    ]
